try: #блок, де може виникнути помилка
    number = int(input("Введіть число: "))
    print("Введене число:", number)
except: #перехоплення та обробка всіх винятків
    print("Перетворення прошло невдало")
print("Завершення програми")


number = int(input("Введіть число: "))